model:
    arch: unet
data:
    dataset: bladder
    train_split: train_aug
    split: val
    img_rows: 'same'
    img_cols: 'same'
training:
    epoch: 200
    batch_size: 4
    report_freq: 10
    n_workers: 2
    multi_gpus: False
    double_down_channel: True
    grad_clip: 3
    max_patience: 10
    model_optimizer:
        name: 'adam'
        lr: 3.0e-3
        weight_decay: 1.0e-4
    loss:
        name: 'dice_loss'
        aux_weight: 0
    backbone:
    lr_schedule:
        name: 'cos'
        T_max: 100
    resume: