model:
    arch: nas-unet
data:
    dataset: bladder
    train_split: train_aug
    split: val
    img_rows: 'same'
    img_cols: 'same'
searching:
    init_channels: 16
    depth: 4
    epoch: 300
    batch_size: 2
    report_freq: 20
    n_workers: 2
    alpha_begin: 10
    max_patience: 40
    gpu: True
    multi_gpus: True
    sharing_normal: True
    double_down_channel: False
    meta_node_num: 3
    grad_clip: 5
    train_portion: 0.5
    model_optimizer:
        name: 'adabound'
        lr: 1.0e-3
        weight_decay: 3.0e-4
    arch_optimizer:
        name: 'adam'
        lr: 3.0e-4
        weight_decay: 5.0e-3
    loss:
        name: 'dice_loss'
        size_average: False
        aux_weight:
    resume:
training:
    geno_type: NASUNET
    init_channels: 16
    depth: 5
    epoch: 200
    batch_size: 1
    report_freq: 20
    n_workers: 2
    gpu: True
    multi_gpus: False
    double_down_channel: False
    grad_clip: 2
    max_patience: 20
    model_optimizer:
        name: 'adam'
        lr: 1.0e-3
        weight_decay: 1.0e-4
    loss:
        name: 'dice_loss'
        aux_weight: 0
    backbone:
    lr_schedule:
        name: 'poly_lr'
        max_iter: 100
    resume:
